[book]
authors = ["dantezhu"]
language = "en"
title = "把时间当作朋友"
src = "."

[output.html]
additional-css = ["custom/custom.css"]

[output.html.print]
enable = false

# 依赖 HollowMan6/mdbook-pdf
# mdbook build
# [output.pdf]
